// Writes data/recorded/index.ts: static imports of every recording so they are bundled into the
// serverless functions (no runtime filesystem reads, which Vercel would not trace).
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join(process.cwd(), 'data', 'recorded');
const lines: string[] = ['// Generated by scripts/index-recordings.ts. Do not edit; run `npm run index-recordings`.', ''];
const entries: string[] = [];
let n = 0;
for (const sample of fs.readdirSync(ROOT).filter((d) => fs.statSync(path.join(ROOT, d)).isDirectory()).sort()) {
  for (const f of fs.readdirSync(path.join(ROOT, sample)).filter((f) => f.endsWith('.json')).sort()) {
    const id = `r${n++}`;
    lines.push(`import ${id} from './${sample}/${f}';`);
    entries.push(`  '${sample}/${f.replace(/\.json$/, '')}': ${id},`);
  }
}
lines.push('', 'export const recordings: Record<string, unknown> = {', ...entries, '};', '');
fs.writeFileSync(path.join(ROOT, 'index.ts'), lines.join('\n'));
console.log(`Indexed ${n} recordings.`);
