// Generated by scripts/index-recordings.ts. Do not edit; run `npm run index-recordings`.

import r0 from './scholarship/classify.json';
import r1 from './scholarship/cr.json';
import r2 from './scholarship/digitise.application_form.json';
import r3 from './scholarship/discovery.json';
import r4 from './scholarship/fields.json';
import r5 from './scholarship/fix.AMB-FR-GRV-001-quickly.json';
import r6 from './scholarship/fix.COV-GO-7.3.json';
import r7 from './scholarship/fix.REV-1.json';
import r8 from './scholarship/impact.COR2.json';
import r9 from './scholarship/interview.json';
import r10 from './scholarship/narrative.asis.json';
import r11 from './scholarship/narrative.introduction.json';
import r12 from './scholarship/narrative.tobe.json';
import r13 from './scholarship/permissions.json';
import r14 from './scholarship/questions.json';
import r15 from './scholarship/reconcile.json';
import r16 from './scholarship/requirements.ADM.json';
import r17 from './scholarship/requirements.APP.json';
import r18 from './scholarship/requirements.DOC.json';
import r19 from './scholarship/requirements.GRV.json';
import r20 from './scholarship/requirements.NFR.json';
import r21 from './scholarship/requirements.NOT.json';
import r22 from './scholarship/requirements.PAY.json';
import r23 from './scholarship/requirements.REG.json';
import r24 from './scholarship/requirements.RPT.json';
import r25 from './scholarship/requirements.VER.json';
import r26 from './scholarship/review.json';
import r27 from './scholarship/rules.json';
import r28 from './scholarship/translate.json';
import r29 from './scholarship/workflow.json';

export const recordings: Record<string, unknown> = {
  'scholarship/classify': r0,
  'scholarship/cr': r1,
  'scholarship/digitise.application_form': r2,
  'scholarship/discovery': r3,
  'scholarship/fields': r4,
  'scholarship/fix.AMB-FR-GRV-001-quickly': r5,
  'scholarship/fix.COV-GO-7.3': r6,
  'scholarship/fix.REV-1': r7,
  'scholarship/impact.COR2': r8,
  'scholarship/interview': r9,
  'scholarship/narrative.asis': r10,
  'scholarship/narrative.introduction': r11,
  'scholarship/narrative.tobe': r12,
  'scholarship/permissions': r13,
  'scholarship/questions': r14,
  'scholarship/reconcile': r15,
  'scholarship/requirements.ADM': r16,
  'scholarship/requirements.APP': r17,
  'scholarship/requirements.DOC': r18,
  'scholarship/requirements.GRV': r19,
  'scholarship/requirements.NFR': r20,
  'scholarship/requirements.NOT': r21,
  'scholarship/requirements.PAY': r22,
  'scholarship/requirements.REG': r23,
  'scholarship/requirements.RPT': r24,
  'scholarship/requirements.VER': r25,
  'scholarship/review': r26,
  'scholarship/rules': r27,
  'scholarship/translate': r28,
  'scholarship/workflow': r29,
};
